### PR TITLE
Fixes for issues: #1, #4, #5

### LINKED ISSUE #1: Aceitar números com mais do que 2 casas decimais
### Descrição do Problema

Atualmente, os Term nodes aceitam números com até 2 casas decimais. Deveríamos aceitar mais, por exemplo, 8.

Image

### LINKED ISSUE #4: Colocar `*` como operação padrão do Expression node
### Descrição da Sugestão

Atualmente, a operação padrão dos Expression nodes é `+` (Soma). Deveríamos usar o mais comum `*`.

Image

### LINKED ISSUE #5: Fazer a tecla `Enter` acionar o botão `Add` durante a adição de nós
### Descrição da Sugestão

Fazer com que o apertar da tecla `Enter` acione a operação `Add` na modal de adição de nós.

Image

### PR DESCRIPTION
**Pull request by davijannotti**
Resolve #1
Resolve #4
Resolve #5

### CODE REVIEW

File: src/exprtree.rs [hunk 1]
```diff
@@ -12,7 +12,7 @@ pub struct ExpressionTree<OriginType: Hash> {
 impl<OriginType: Hash> Default for ExpressionTree<OriginType> {
     fn default() -> Self {
         Self {
-            join_op: Default::default(),
+            join_op: Operation::Mul,
```
Comment (Syndelis) [inline src/exprtree.rs]: Acho melhor mudar o `#[default]` do `Operation`, ao invés de mudar pontualmente aqui

Comment (davijannotti) [reply src/exprtree.rs]: Resolvido no commit: c9b177c80498a0be17c83440864695a7a98bf963

**Review by Syndelis — APPROVED** [review]

**Review by Syndelis — APPROVED** [review]
